### ISSUE TITLE
Queue for course enrollment

### ISSUE THREAD

**Issue by meepoSenpai** [fsr/course-management#11]
If a course is full, the user should be added to a queue.

**Comment by JustusAdam** [comment]
Queue added as of 6025d8592a46224cab3affd17857d5ad79496be9.

Functionality for using the queue remains to be implemented.

**The queue is currently not used yet.** 

The feature is not used yet because of uncertainty where it should run. The important decision to be made here is whether moving people from queue into the course should be done on the model (and thus always) or in the view. Do we want to preserve ourselves some administrative functionality on the model or enforce the moving up to happen every time a student unregisters from a course?

**Comment by Feliix42** [comment]
@manuelthieme implemented this a long while ago in b1cc0a86f7ba7cc2b331013775a3e53d279f0cff and I tweaked the functionality somewhat in later commits.
