### ISSUE TITLE
Release & Deployment

### ISSUE THREAD

**Issue by Feliix42** [fsr/course-management#28]
The new semester is approaching and the goal was to have the new system up and running for the upcoming course cycle.
@JustusAdam do you think we will be able to sit together with @sebschrader and deploy the enrollment system in time for the summer term enrollments? Or is there too much left to fix?

**Comment by JustusAdam** [comment]
You should talk to @manuelthieme, he has asked me this question many times. We need the object level permissions t be reflected in the UI which @manuelthieme wanted to fix, I am not sure he's done it yet. Beyond that the new style from the corporate design has to be incorporated. AFAIK Lucas and Lars have finished it, now it needs to be integrated and tested.

**Comment by Feliix42** [comment]
FYI I posted this on behalf of @manuelthieme (he won't be around next week).

The corporate design has been pushed to [fsr/corporate-web-design](https://github.com/fsr/corporate-web-design) and seems to be ready for integration (@LarsEngeln, @lucasvog?)

**Comment by Lodifice** [comment]
( @JustusAdam ) regarding the object level permissions not being reflected in the UI, @manuelthieme sent you a question where exactly the problems occur some weeks ago.
We couldn't figure out any problems.

You may also refer to #27 which does not give a detailed explanation either.

**Comment by JustusAdam** [comment]
There is no "problem that occurs". At least none that I can tell you. You added the object level permissions, the task now was to figure out which UI elements link to pages or actions which are guarded with object level permissions and hide them.
I cannot tell you which exact elements those are, because I don't know. I thought I had explained this to @manuelthieme, perhaps not in an email but in person multiple times.

**Comment by Feliix42** [comment]
So what needs to be done before the launch is going to happen? Is #27 part of the _Launch_ milestone?

The [corresponding milestone](https://github.com/fsr/course-management/milestones/Launch) contains #24 and #25 right now.
I just want to get a clear view of the TODOs.

**Comment by Lodifice** [comment]
#27 is not, but should be part of *launch*.

However, @manuelthieme and me could not figure out any visible UI elemtens that link to inaccessible pages (at least not due to object level permissions). We thought @JustusAdam had some specific problem instances in mind. It is totally possible that there exist no such errors since I also changed some code for creating overviews etc.

**Comment by JustusAdam** [comment]
Okay. I didn't know you looked at it already. You guys didn't inform me. Since this seems to be done that should be pretty much it.

**Comment by Feliix42** [comment]
After we deployed a Alpha or Beta version of the CM, I will close this. Everything that needs to be done is listed [here](https://github.com/fsr/course-management/milestones/Version%201.0%20stable).
