### ISSUE TITLE
Email Verification

### ISSUE THREAD

**Issue by SaschaPeukert** [fsr/course-management#29]
Hey,

My verification mail looks like this:

"Dear Sascha,

you have successfully signed up for your iFSR Course Enrollment system account.
Note that you need to verify your account before you will be able to log in.

Please click the following link to activate your account:
/kurse/accounts/verify/student/?token= " ....<Some Stuff>

I suggest that you add in the complete url (the first part) to this link  ;-)

**Comment by Feliix42** [comment]
I think this can be fixed by "hard-coding" the URL into **course-management/user/views/register.py** in the function `verification_mail()`.

The definition of _activateurl_ would look like this:
```python
activateurl = 'https://ifsr.de' + reverse('verify', args=[type_]) + '?token=' + user_token
```

The problem with hardcoding the URL is that it is - well - hardcoded. We might want to put the URL `'https://ifsr.de'` as global variable into **course/settings.py** (as `BASE_URL`?) so that it can be easily changed to a localhost address in the dev environment.

**Comment by JustusAdam** [comment]
isn't there some global base url somewhere already, or am I mistaken in that?

**Comment by h4llow3En** [comment]
Still does not work

**Comment by manuelthieme** [comment]
In local tests "localhost:8000" was added. Don't know why this doesn't work anywhere else.

**Comment by h4llow3En** [comment]
Fixed
Django needed to be restarted before changes are applied
