### ISSUE TITLE
creation of schedule fails

### ISSUE THREAD

**Issue by manuelthieme** [fsr/course-management#37]
When creating a new course, a schedule is automatically created but the type property of this schedule is a full html line.

**Comment by Feliix42** [comment]
Seems like I've been able to fix the problem, at least temporarily. The problem was in [this line](https://github.com/fsr/course-management/blob/4217610180689a11e4161b41fd2b746deaafec11/course/views/course.py#L143).

The `schedule_type` field transmitted in the POST request was `'W'` when a weekly schedule was chosen. But then, for some reason, the content of `form['schedule_type']` after that specific line had changed to the full HTML code of the select box for the schedule type:
```
<select id="id_schedule_type" name="schedule_type">\n<option value="W" selected="selected">w\xc3\xb6chentlich</option>\n<option value="O">einmalig</option>\n</select>
```

After changing line 147 to set the schedule type based on `request.POST['schedule_type']` it seems to work.
