### ISSUE TITLE
verification does not activate account in all cases

### ISSUE THREAD

**Issue by manuelthieme** [fsr/course-management#40]
I Have no Idea... sometimes it works, other times it doesn't

**Comment by fer-rum** [comment]
Can confirm. After activation my account still registers as inactive.

**Comment by manuelthieme** [comment]
Could reproduce... yay.

If you sign up with your s-number, two mails are sent. One to your regular mail adress and one to your zih mail. By following the activationlink in the mail in your zih mailbox, your account gets validated as student but not activated.

Tried to find the point in code where that happens, but without luck so far.

**Comment by h4llow3En** [comment]
Only one mail should be send. Only sXXXXXXX@... if s-Number is provided

**Comment by h4llow3En** [comment]
works not on ifs.de... don't know why

**Comment by kiliankoe** [comment]
> Only one mail should be send.

But the site itself states that two mails are sent, which worked just fine on my end.

**Comment by Feliix42** [comment]
The problem is that you _have_ to follow a certain order when activating the account. First step is to verify the non-TU-account, second the TU account since the latter will not set your account to active.

So if the mail address you entered is you s-number, you run into a problem since the site identifies the university mail account and only sends the second "type" of mail, the one that validates the student account status but does not activate the account.

@h4llow3En presumably fixed this in 471f3cb, it just needs to be deployed.

**Comment by h4llow3En** [comment]
Fixed
Django needed to be restarted before changes are applied
