### ISSUE TITLE
Subjects Overview Inconsistent

### ISSUE THREAD

**Issue by Feliix42** [fsr/course-management#50]
Right now, [https://ifsr.de/kurse/](https://ifsr.de/kurse/) and  [https://www.ifsr.de/kurse/subject/overview/](https://www.ifsr.de/kurse/subject/overview/) display the exact same content but in a different shape. While the _Subjects_ Overview displays the courses nicely as a table, the _Home Page_ shows no layout at all. 

This is due to the fact that `kurse/`displays the courses as `<div>` while the `kurse/subject/overview/` page uses a `<table>`.

**Comment by JustusAdam** [comment]
I think the actual issue here is that there's no well thought out concept for the home page yet. It is by no means set in stone that the home page has to only contain a subjects overview, not even that it has to contain a subjects overview at all.

I think we should first make a solid concept for the home page before we start going hard on custom style.
