### ISSUE TITLE
Front page

### ISSUE THREAD

**Issue by Feliix42** [fsr/course-management#64]
Currently, the front page is just a duplicate of the _Subjects_ overview.

I'd like to turn this page into a real start page with some greeting message and a "Message Of The Day" which can be changed by admins. 

(I'm also open for suggestions.)

**Comment by sjaster** [comment]
Would propably just use a generic message as "Message of the Day", which youll change like 3 times a year. If you use it like a little newsfeed it's likely to move the task from one date to another because it has a low priority.

Maybe just add another box as "Message of the Day" - Box on Top of the subject box. Wouldn't recommend to delete the subject box cause it provides a good summary for all the stuff that's available.

**Comment by Feliix42** [comment]
Yeah the basic idea was to have a single text block whose contents can be changed by an admin and that contains just basic information like "when do the next courses start?", "when will enrolment start?" and things like that. 

Could be implemented as database field (which imho is not the best option for a single piece of data) or using a text file, which might be even worse as it would have to be opened during every page load. 😅
