### ISSUE TITLE
course notification does not work

### ISSUE THREAD

**Issue by Necktschnagge** [fsr/course-management#83]
I've tried several times (3x I think) to send my course
(https://www.ifsr.de/kurse/course/50/)
a message, but despite I always saw the "message successfully delivered"-screen after pressing the send button, there was no message sent at all, neither to the attendees nor to me, like it was the case in history.

**Comment by Feliix42** [comment]
As far as I can tell from the server logs, a bunch of mails have been sent out by the system. As I am not sure whether this problem is really a code issue (notification worked when I tested it right now), I suggest you drop a mail at `root@ifsr.de` with some more information (rough time of your transmission, any additional information, ...) so we can isolate the issue and resolve it. :)
