### ISSUE TITLE
Update to Django 2.*

### ISSUE THREAD

**Issue by Feliix42** [fsr/course-management#84]
Currently, Django `1.8.*` is used. But as this version is already almost 2 years old, we should consider updating to a more recent version, either `2.0.*` or `2.1.*`. This can be done according to the [Upgrade Instructions](https://docs.djangoproject.com/en/2.0/howto/upgrade-version/).

**Comment by mhaehnel** [comment]
Since beginning of August we run on Django 1.11 successfully. 

While Django 1.11 has LTS until 2020 it would be nice to be prepared once that runs out. Currently I see a few blockers (such as https://github.com/deschler/django-modeltranslation/issues/472) that could prevent us from upgrading. 

I do not know if we need to update anything within the application to be compatible to Django 2.x

**Comment by Feliix42** [comment]
This fas been fixed in d354cdd0f936f217f608ade53c80cd0e0b8a5727 :)
